server:
  port: 9999



# Eureka集成
eureka:
  client:
    register-with-eureka: false # 不向eureka注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true
