server:
  port: 8001

mybatis:
  mapper-locations: classpath:com/yuan/springcloud/dao/*.xml
  type-aliases-package: com.yuan.springcloud
  config-location: classpath:com/yuan/springcloud/mybatis-config.xml


#   数据源
spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    #Eureka的配置,服务注册到哪里？
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 # 修改默认的描述信息
# info
info:
  app.name: yuan_tangbo
  company.name: ZJU


